### ISSUE TITLE
[REQ] ImageList Support More pattern

### ISSUE THREAD

**Issue by east4ming** [eraser-dev/eraser#1114]
### What kind of request is this?

New feature

### What is your request or suggestion?

I would like Eraser to add this "ImageList Support More Patterns" so than I can use it in my scenrio:

I can delete images based on X.Y.Z image tag versions.
For example, I can specify that I want to delete all X.Y-1 minor version images. Or delete all X-1 major version images.

When using Eraser the `ImageList` has only detail tag or '*'.

Now state:

```
apiVersion: eraser.sh/v1alpha1
kind: ImageList
metadata:
  name: imagelist
spec:
  images:
    - docker.io/library/alpine:3.7.3   # use "*" for all non-running images
```

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.
