### ISSUE TITLE
Eraser error

### ISSUE THREAD

**Issue by whober0521** [eraser-dev/eraser#824]
**What steps did you take and what happened:**
`kubectl apply -f ./"${eraserFile}"`

eraserFile:
```
apiVersion: eraser.sh/v1alpha1
kind: ImageList
metadata:
  name: imagelist
spec:
  # POAM hotfix
  images:
    - arosvc.azurecr.io/genevasecpackinstall@sha256:40448ad550751e2255c86d814228e5654422faba1d5fb774ce15ccae7e24e89d
    - arosvc.azurecr.io/genevasecpackinstall@sha256:d174c3b97cc9fd95fad3d518bb3f7e72f4a5e1c7e436b34fb9525977c8633e05
```

after running above command, it's still in the crictl image list
```
# crictl images
IMAGE                                                                         TAG                                    IMAGE ID            SIZE
arosvc.azurecr.io/acskeyvaultagent                                            mariner_20230706.2                     3e170db1052ed       118MB
arosvc.azurecr.io/distroless/genevamdm                                        2.2023.721.1630-e50918-20230721t1737   247206bad4692       23MB
arosvc.azurecr.io/distroless/genevamdsd                                       mariner_20230719.1                     a83452a979ef5       93.9MB
arosvc.azurecr.io/genevasecpackinstall                                        master_20230706.1                      0af62431131aa       52MB
arosvc.azurecr.io/oss/fluent/fluent-bit                                       2.0.14-6                               32f6ed5db233e       33.4MB
arosvc.azurecr.io/shared/prom-mdm-converter                                   distroless-2.0.master.20230611.1       9e9b79aa9e357       8.91MB
```

**What did you expect to happen:**
it should no longer show in  crictl image list

**Anything else you would like to add:**
checked logs in eraser controller, it shows the following error:
`{"level":"error","ts":1691210574.7192776,"msg":"Reconciler error","controller":"imagejob-controller","object":{"name":"imagejob-bpxzn"},"namespace":"","name":"imagejob-bpxzn","reconcileID":"ab5fd3a0-adcf-43f6-802d-48ababc0bbec","error":"reconcile new: PodTemplate \"imagejob-bpxzn\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}`

**Environment:**
Production

- Eraser version:
Image:           mcr.microsoft.com/oss/eraser/eraser-manager:v1.1.1

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"94c50547e633f1db5d4c56b2b305670e14987d59", GitTreeState:"clean", BuildDate:"2023-06-12T18:46:30Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
